const std = @import("std");
const dvui = @import("dvui");

pub const keycodes: [252][]const u8 = .{
    "ESC",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "MINUS",
    "EQUAL",
    "BACKSPACE",
    "TAB",
    "Q",
    "W",
    "E",
    "R",
    "T",
    "Y",
    "U",
    "I",
    "O",
    "P",
    "LEFTBRACE",
    "RIGHTBRACE",
    "ENTER",
    "LEFTCTRL",
    "A",
    "S",
    "D",
    "F",
    "G",
    "H",
    "J",
    "K",
    "L",
    "SEMICOLON",
    "APOSTROPHE",
    "GRAVE",
    "LEFTSHIFT",
    "BACKSLASH",
    "Z",
    "X",
    "C",
    "V",
    "B",
    "N",
    "M",
    "COMMA",
    "DOT",
    "SLASH",
    "RIGHTSHIFT",
    "KPASTERISK",
    "LEFTALT",
    "SPACE",
    "CAPSLOCK",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "NUMLOCK",
    "SCROLLLOCK",
    "KP7",
    "KP8",
    "KP9",
    "KPMINUS",
    "KP4",
    "KP5",
    "KP6",
    "KPPLUS",
    "KP1",
    "KP2",
    "KP3",
    "KP0",
    "KPDOT",
    "ZENKAKUHANKAKU",
    "102ND",
    "F11",
    "F12",
    "RO",
    "KATAKANA",
    "HIRAGANA",
    "HENKAN",
    "KATAKANAHIRAGANA",
    "MUHENKAN",
    "KPJPCOMMA",
    "KPENTER",
    "RIGHTCTRL",
    "KPSLASH",
    "SYSRQ",
    "RIGHTALT",
    "LINEFEED",
    "HOME",
    "UP",
    "PAGEUP",
    "LEFT",
    "RIGHT",
    "END",
    "DOWN",
    "PAGEDOWN",
    "INSERT",
    "DELETE",
    "MACRO",
    "MUTE",
    "VOLUMEDOWN",
    "VOLUMEUP",
    "POWER",
    "KPEQUAL",
    "KPPLUSMINUS",
    "PAUSE",
    "SCALE",
    "KPCOMMA",
    "HANGEUL",
    "HANGUEL",
    "HANJA",
    "YEN",
    "LEFTMETA",
    "RIGHTMETA",
    "COMPOSE",
    "STOP",
    "AGAIN",
    "PROPS",
    "UNDO",
    "FRONT",
    "COPY",
    "OPEN",
    "PASTE",
    "FIND",
    "CUT",
    "HELP",
    "MENU",
    "CALC",
    "SETUP",
    "SLEEP",
    "WAKEUP",
    "FILE",
    "SENDFILE",
    "DELETEFILE",
    "XFER",
    "PROG1",
    "PROG2",
    "WWW",
    "MSDOS",
    "COFFEE",
    "SCREENLOCK",
    "ROTATE_DISPLAY",
    "DIRECTION",
    "CYCLEWINDOWS",
    "MAIL",
    "BOOKMARKS",
    "COMPUTER",
    "BACK",
    "FORWARD",
    "CLOSECD",
    "EJECTCD",
    "EJECTCLOSECD",
    "NEXTSONG",
    "PLAYPAUSE",
    "PREVIOUSSONG",
    "STOPCD",
    "RECORD",
    "REWIND",
    "PHONE",
    "ISO",
    "CONFIG",
    "HOMEPAGE",
    "REFRESH",
    "EXIT",
    "MOVE",
    "EDIT",
    "SCROLLUP",
    "SCROLLDOWN",
    "KPLEFTPAREN",
    "KPRIGHTPAREN",
    "NEW",
    "REDO",
    "F13",
    "F14",
    "F15",
    "F16",
    "F17",
    "F18",
    "F19",
    "F20",
    "F21",
    "F22",
    "F23",
    "F24",
    "PLAYCD",
    "PAUSECD",
    "PROG3",
    "PROG4",
    "ALL_APPLICATIONS",
    "DASHBOARD",
    "SUSPEND",
    "CLOSE",
    "PLAY",
    "FASTFORWARD",
    "BASSBOOST",
    "PRINT",
    "HP",
    "CAMERA",
    "SOUND",
    "QUESTION",
    "EMAIL",
    "CHAT",
    "SEARCH",
    "CONNECT",
    "FINANCE",
    "SPORT",
    "SHOP",
    "ALTERASE",
    "CANCEL",
    "BRIGHTNESSDOWN",
    "BRIGHTNESSUP",
    "MEDIA",
    "SWITCHVIDEOMODE",
    "KBDILLUMTOGGLE",
    "KBDILLUMDOWN",
    "KBDILLUMUP",
    "SEND",
    "REPLY",
    "FORWARDMAIL",
    "SAVE",
    "DOCUMENTS",
    "BATTERY",
    "BLUETOOTH",
    "WLAN",
    "UWB",
    "VIDEO_NEXT",
    "VIDEO_PREV",
    "BRIGHTNESS_CYCLE",
    "BRIGHTNESS_AUTO",
    "BRIGHTNESS_ZERO",
    "DISPLAY_OFF",
    "WWAN",
    "WIMAX",
    "RFKILL",
    "MICMUTE",
    "M1",
    "M2",
    "M3",
    "M4",
    "M5",
};

pub const keycode_to_xkb = std.StaticStringMap([]const u8).initComptime(.{
    .{ "ESC", "ESC" },
    .{ "1", "AE01" },
    .{ "2", "AE02" },
    .{ "3", "AE03" },
    .{ "4", "AE04" },
    .{ "5", "AE05" },
    .{ "6", "AE06" },
    .{ "7", "AE07" },
    .{ "8", "AE08" },
    .{ "9", "AE09" },
    .{ "0", "AE10" },
    .{ "MINUS", "AE11" },
    .{ "EQUAL", "AE12" },
    .{ "BACKSPACE", "BKSP" },
    .{ "TAB", "TAB" },
    .{ "Q", "AD01" },
    .{ "W", "AD02" },
    .{ "E", "AD03" },
    .{ "R", "AD04" },
    .{ "T", "AD05" },
    .{ "Y", "AD06" },
    .{ "U", "AD07" },
    .{ "I", "AD08" },
    .{ "O", "AD09" },
    .{ "P", "AD10" },
    .{ "LEFTBRACE", "AD11" },
    .{ "RIGHTBRACE", "AD12" },
    .{ "ENTER", "RTRN" },
    .{ "LEFTCTRL", "LCTL" },
    .{ "A", "AC01" },
    .{ "S", "AC02" },
    .{ "D", "AC03" },
    .{ "F", "AC04" },
    .{ "G", "AC05" },
    .{ "H", "AC06" },
    .{ "J", "AC07" },
    .{ "K", "AC08" },
    .{ "L", "AC09" },
    .{ "SEMICOLON", "AC10" },
    .{ "APOSTROPHE", "AC11" },
    .{ "GRAVE", "TLDE" },
    .{ "LEFTSHIFT", "LFSH" },
    .{ "BACKSLASH", "BKSL" },
    .{ "Z", "AB01" },
    .{ "X", "AB02" },
    .{ "C", "AB03" },
    .{ "V", "AB04" },
    .{ "B", "AB05" },
    .{ "N", "AB06" },
    .{ "M", "AB07" },
    .{ "COMMA", "AB08" },
    .{ "DOT", "AB09" },
    .{ "SLASH", "AB10" },
    .{ "RIGHTSHIFT", "RTSH" },
    .{ "KPASTERISK", "KPMU" },
    .{ "LEFTALT", "LALT" },
    .{ "SPACE", "SPCE" },
    .{ "CAPSLOCK", "CAPS" },
    .{ "F1", "FK01" },
    .{ "F2", "FK02" },
    .{ "F3", "FK03" },
    .{ "F4", "FK04" },
    .{ "F5", "FK05" },
    .{ "F6", "FK06" },
    .{ "F7", "FK07" },
    .{ "F8", "FK08" },
    .{ "F9", "FK09" },
    .{ "F10", "FK10" },
    .{ "NUMLOCK", "NMLK" },
    .{ "SCROLLLOCK", "SCLK" },
    .{ "KP7", "KP7" },
    .{ "KP8", "KP8" },
    .{ "KP9", "KP9" },
    .{ "KPMINUS", "KPSU" },
    .{ "KP4", "KP4" },
    .{ "KP5", "KP5" },
    .{ "KP6", "KP6" },
    .{ "KPPLUS", "KPAD" },
    .{ "KP1", "KP1" },
    .{ "KP2", "KP2" },
    .{ "KP3", "KP3" },
    .{ "KP0", "KP0" },
    .{ "KPDOT", "KPDL" },
    .{ "ZENKAKUHANKAKU", "HZTG" },
    .{ "102ND", "LSGT" },
    .{ "F11", "FK11" },
    .{ "F12", "FK12" },
    .{ "RO", "AB11" },
    .{ "KATAKANA", "KATA" },
    .{ "HIRAGANA", "HIRA" },
    .{ "HENKAN", "HENK" },
    .{ "KATAKANAHIRAGANA", "HKTG" },
    .{ "MUHENKAN", "MUHE" },
    .{ "KPJPCOMMA", "KPJP" },
    .{ "KPENTER", "KPENT" },
    .{ "RIGHTCTRL", "RCTL" },
    .{ "KPSLASH", "KPDV" },
    .{ "SYSRQ", "PRSC" },
    .{ "RIGHTALT", "RALT" },
    .{ "LINEFEED", "LF" },
    .{ "HOME", "HOME" },
    .{ "UP", "UP" },
    .{ "PAGEUP", "PGUP" },
    .{ "LEFT", "LEFT" },
    .{ "RIGHT", "RGHT" },
    .{ "END", "END" },
    .{ "DOWN", "DOWN" },
    .{ "PAGEDOWN", "PGDN" },
    .{ "INSERT", "INS" },
    .{ "DELETE", "DELE" },
    .{ "MACRO", "MACR" },
    .{ "MUTE", "MUTE" },
    .{ "VOLUMEDOWN", "VOL-" },
    .{ "VOLUMEUP", "VOL+" },
    .{ "POWER", "POWR" },
    .{ "KPEQUAL", "KPEQ" },
    .{ "KPPLUSMINUS", "I126" },
    .{ "PAUSE", "PAUS" },
    .{ "SCALE", "I128" },
    .{ "KPCOMMA", "KPCO" },
    .{ "HANGEUL", "HNGL" },
    .{ "HANGUEL", "HNGL" },
    .{ "HANJA", "HJCV" },
    .{ "YEN", "I133" },
    .{ "LEFTMETA", "LWIN" },
    .{ "RIGHTMETA", "RWIN" },
    .{ "COMPOSE", "COMP" },
    .{ "STOP", "STOP" },
    .{ "AGAIN", "AGAI" },
    .{ "PROPS", "PROP" },
    .{ "UNDO", "UNDO" },
    .{ "FRONT", "FRNT" },
    .{ "COPY", "COPY" },
    .{ "OPEN", "OPEN" },
    .{ "PASTE", "PAST" },
    .{ "FIND", "FIND" },
    .{ "CUT", "CUT" },
    .{ "HELP", "HELP" },
    .{ "MENU", "MENU" },
    .{ "CALC", "CALC" },
    .{ "SETUP", "I149" },
    .{ "SLEEP", "I150" },
    .{ "WAKEUP", "I151" },
    .{ "FILE", "I152" },
    .{ "SENDFILE", "I153" },
    .{ "DELETEFILE", "I154" },
    .{ "XFER", "I155" },
    .{ "PROG1", "I156" },
    .{ "PROG2", "I157" },
    .{ "WWW", "I158" },
    .{ "MSDOS", "I159" },
    .{ "COFFEE", "I160" },
    .{ "SCREENLOCK", "I161" },
    .{ "ROTATE_DISPLAY", "I162" },
    .{ "DIRECTION", "I163" },
    .{ "CYCLEWINDOWS", "I164" },
    .{ "MAIL", "I165" },
    .{ "BOOKMARKS", "I166" },
    .{ "COMPUTER", "I167" },
    .{ "BACK", "I168" },
    .{ "FORWARD", "I169" },
    .{ "CLOSECD", "I170" },
    .{ "EJECTCD", "I171" },
    .{ "EJECTCLOSECD", "I172" },
    .{ "NEXTSONG", "I173" },
    .{ "PLAYPAUSE", "I174" },
    .{ "PREVIOUSSONG", "I175" },
    .{ "STOPCD", "I176" },
    .{ "RECORD", "I177" },
    .{ "REWIND", "I178" },
    .{ "PHONE", "I179" },
    .{ "ISO", "I180" },
    .{ "CONFIG", "I181" },
    .{ "HOMEPAGE", "I182" },
    .{ "REFRESH", "I183" },
    .{ "EXIT", "I184" },
    .{ "MOVE", "I185" },
    .{ "EDIT", "I186" },
    .{ "SCROLLUP", "I187" },
    .{ "SCROLLDOWN", "I188" },
    .{ "KPLEFTPAREN", "I189" },
    .{ "KPRIGHTPAREN", "I190" },
    .{ "NEW", "I193" },
    .{ "REDO", "I194" },
    .{ "F13", "FK13" },
    .{ "F14", "FK14" },
    .{ "F15", "FK15" },
    .{ "F16", "FK16" },
    .{ "F17", "FK17" },
    .{ "F18", "FK18" },
    .{ "F19", "FK19" },
    .{ "F20", "FK20" },
    .{ "F21", "FK21" },
    .{ "F22", "FK22" },
    .{ "F23", "FK23" },
    .{ "F24", "FK24" },
    .{ "PLAYCD", "I208" },
    .{ "PAUSECD", "I209" },
    .{ "PROG3", "I210" },
    .{ "PROG4", "I211" },
    .{ "ALL_APPLICATIONS", "I212" },
    .{ "DASHBOARD", "I213" },
    .{ "SUSPEND", "I214" },
    .{ "CLOSE", "I215" },
    .{ "PLAY", "I216" },
    .{ "FASTFORWARD", "I217" },
    .{ "BASSBOOST", "I218" },
    .{ "PRINT", "PRNT" },
    .{ "HP", "I220" },
    .{ "CAMERA", "I221" },
    .{ "SOUND", "I222" },
    .{ "QUESTION", "I223" },
    .{ "EMAIL", "I224" },
    .{ "CHAT", "I225" },
    .{ "SEARCH", "I226" },
    .{ "CONNECT", "I227" },
    .{ "FINANCE", "I228" },
    .{ "SPORT", "I229" },
    .{ "SHOP", "I230" },
    .{ "ALTERASE", "I231" },
    .{ "CANCEL", "I232" },
    .{ "BRIGHTNESSDOWN", "I233" },
    .{ "BRIGHTNESSUP", "I234" },
    .{ "MEDIA", "I235" },
    .{ "SWITCHVIDEOMODE", "I236" },
    .{ "KBDILLUMTOGGLE", "I237" },
    .{ "KBDILLUMDOWN", "I238" },
    .{ "KBDILLUMUP", "I239" },
    .{ "SEND", "I240" },
    .{ "REPLY", "I241" },
    .{ "FORWARDMAIL", "I242" },
    .{ "SAVE", "I243" },
    .{ "DOCUMENTS", "I244" },
    .{ "BATTERY", "I245" },
    .{ "BLUETOOTH", "I246" },
    .{ "WLAN", "I247" },
    .{ "UWB", "I248" },
    .{ "VIDEO_NEXT", "I249" },
    .{ "VIDEO_PREV", "I250" },
    .{ "BRIGHTNESS_CYCLE", "I251" },
    .{ "BRIGHTNESS_AUTO", "I252" },
    .{ "BRIGHTNESS_ZERO", "I253" },
    .{ "DISPLAY_OFF", "I254" },
    .{ "WWAN", "I255" },
    .{ "WIMAX", "I256" },
    .{ "RFKILL", "I257" },
    .{ "MICMUTE", "I258" },
});

pub const xkb_to_keycode = std.StaticStringMap([]const u8).initComptime(.{
    .{ "ESC", "ESC" },
    .{ "AE01", "1" },
    .{ "AE02", "2" },
    .{ "AE03", "3" },
    .{ "AE04", "4" },
    .{ "AE05", "5" },
    .{ "AE06", "6" },
    .{ "AE07", "7" },
    .{ "AE08", "8" },
    .{ "AE09", "9" },
    .{ "AE10", "0" },
    .{ "AE11", "MINUS" },
    .{ "AE12", "EQUAL" },
    .{ "BKSP", "BACKSPACE" },
    .{ "TAB", "TAB" },
    .{ "AD01", "Q" },
    .{ "AD02", "W" },
    .{ "AD03", "E" },
    .{ "AD04", "R" },
    .{ "AD05", "T" },
    .{ "AD06", "Y" },
    .{ "AD07", "U" },
    .{ "AD08", "I" },
    .{ "AD09", "O" },
    .{ "AD10", "P" },
    .{ "AD11", "LEFTBRACE" },
    .{ "AD12", "RIGHTBRACE" },
    .{ "RTRN", "ENTER" },
    .{ "LCTL", "LEFTCTRL" },
    .{ "AC01", "A" },
    .{ "AC02", "S" },
    .{ "AC03", "D" },
    .{ "AC04", "F" },
    .{ "AC05", "G" },
    .{ "AC06", "H" },
    .{ "AC07", "J" },
    .{ "AC08", "K" },
    .{ "AC09", "L" },
    .{ "AC10", "SEMICOLON" },
    .{ "AC11", "APOSTROPHE" },
    .{ "TLDE", "GRAVE" },
    .{ "LFSH", "LEFTSHIFT" },
    .{ "BKSL", "BACKSLASH" },
    .{ "AB01", "Z" },
    .{ "AB02", "X" },
    .{ "AB03", "C" },
    .{ "AB04", "V" },
    .{ "AB05", "B" },
    .{ "AB06", "N" },
    .{ "AB07", "M" },
    .{ "AB08", "COMMA" },
    .{ "AB09", "DOT" },
    .{ "AB10", "SLASH" },
    .{ "RTSH", "RIGHTSHIFT" },
    .{ "KPMU", "KPASTERISK" },
    .{ "LALT", "LEFTALT" },
    .{ "SPCE", "SPACE" },
    .{ "CAPS", "CAPSLOCK" },
    .{ "FK01", "F1" },
    .{ "FK02", "F2" },
    .{ "FK03", "F3" },
    .{ "FK04", "F4" },
    .{ "FK05", "F5" },
    .{ "FK06", "F6" },
    .{ "FK07", "F7" },
    .{ "FK08", "F8" },
    .{ "FK09", "F9" },
    .{ "FK10", "F10" },
    .{ "NMLK", "NUMLOCK" },
    .{ "SCLK", "SCROLLLOCK" },
    .{ "KP7", "KP7" },
    .{ "KP8", "KP8" },
    .{ "KP9", "KP9" },
    .{ "KPSU", "KPMINUS" },
    .{ "KP4", "KP4" },
    .{ "KP5", "KP5" },
    .{ "KP6", "KP6" },
    .{ "KPAD", "KPPLUS" },
    .{ "KP1", "KP1" },
    .{ "KP2", "KP2" },
    .{ "KP3", "KP3" },
    .{ "KP0", "KP0" },
    .{ "KPDL", "KPDOT" },
    .{ "HZTG", "ZENKAKUHANKAKU" },
    .{ "LSGT", "102ND" },
    .{ "FK11", "F11" },
    .{ "FK12", "F12" },
    .{ "AB11", "RO" },
    .{ "KATA", "KATAKANA" },
    .{ "HIRA", "HIRAGANA" },
    .{ "HENK", "HENKAN" },
    .{ "HKTG", "KATAKANAHIRAGANA" },
    .{ "MUHE", "MUHENKAN" },
    .{ "KPJP", "KPJPCOMMA" },
    .{ "KPENT", "KPENTER" },
    .{ "RCTL", "RIGHTCTRL" },
    .{ "KPDV", "KPSLASH" },
    .{ "PRSC", "SYSRQ" },
    .{ "RALT", "RIGHTALT" },
    .{ "LF", "LINEFEED" },
    .{ "HOME", "HOME" },
    .{ "UP", "UP" },
    .{ "PGUP", "PAGEUP" },
    .{ "LEFT", "LEFT" },
    .{ "RGHT", "RIGHT" },
    .{ "END", "END" },
    .{ "DOWN", "DOWN" },
    .{ "PGDN", "PAGEDOWN" },
    .{ "INS", "INSERT" },
    .{ "DELE", "DELETE" },
    .{ "MACR", "MACRO" },
    .{ "MUTE", "MUTE" },
    .{ "VOL-", "VOLUMEDOWN" },
    .{ "VOL+", "VOLUMEUP" },
    .{ "POWR", "POWER" },
    .{ "KPEQ", "KPEQUAL" },
    .{ "I126", "KPPLUSMINUS" },
    .{ "PAUS", "PAUSE" },
    .{ "I128", "SCALE" },
    .{ "KPCO", "KPCOMMA" },
    .{ "HNGL", "HANGEUL" },
    .{ "HNGL", "HANGUEL" },
    .{ "HJCV", "HANJA" },
    .{ "I133", "YEN" },
    .{ "LWIN", "LEFTMETA" },
    .{ "RWIN", "RIGHTMETA" },
    .{ "COMP", "COMPOSE" },
    .{ "STOP", "STOP" },
    .{ "AGAI", "AGAIN" },
    .{ "PROP", "PROPS" },
    .{ "UNDO", "UNDO" },
    .{ "FRNT", "FRONT" },
    .{ "COPY", "COPY" },
    .{ "OPEN", "OPEN" },
    .{ "PAST", "PASTE" },
    .{ "FIND", "FIND" },
    .{ "CUT", "CUT" },
    .{ "HELP", "HELP" },
    .{ "MENU", "MENU" },
    .{ "CALC", "CALC" },
    .{ "I149", "SETUP" },
    .{ "I150", "SLEEP" },
    .{ "I151", "WAKEUP" },
    .{ "I152", "FILE" },
    .{ "I153", "SENDFILE" },
    .{ "I154", "DELETEFILE" },
    .{ "I155", "XFER" },
    .{ "I156", "PROG1" },
    .{ "I157", "PROG2" },
    .{ "I158", "WWW" },
    .{ "I159", "MSDOS" },
    .{ "I160", "COFFEE" },
    .{ "I161", "SCREENLOCK" },
    .{ "I162", "ROTATE_DISPLAY" },
    .{ "I163", "DIRECTION" },
    .{ "I164", "CYCLEWINDOWS" },
    .{ "I165", "MAIL" },
    .{ "I166", "BOOKMARKS" },
    .{ "I167", "COMPUTER" },
    .{ "I168", "BACK" },
    .{ "I169", "FORWARD" },
    .{ "I170", "CLOSECD" },
    .{ "I171", "EJECTCD" },
    .{ "I172", "EJECTCLOSECD" },
    .{ "I173", "NEXTSONG" },
    .{ "I174", "PLAYPAUSE" },
    .{ "I175", "PREVIOUSSONG" },
    .{ "I176", "STOPCD" },
    .{ "I177", "RECORD" },
    .{ "I178", "REWIND" },
    .{ "I179", "PHONE" },
    .{ "I180", "ISO" },
    .{ "I181", "CONFIG" },
    .{ "I182", "HOMEPAGE" },
    .{ "I183", "REFRESH" },
    .{ "I184", "EXIT" },
    .{ "I185", "MOVE" },
    .{ "I186", "EDIT" },
    .{ "I187", "SCROLLUP" },
    .{ "I188", "SCROLLDOWN" },
    .{ "I189", "KPLEFTPAREN" },
    .{ "I190", "KPRIGHTPAREN" },
    .{ "I193", "NEW" },
    .{ "I194", "REDO" },
    .{ "FK13", "F13" },
    .{ "FK14", "F14" },
    .{ "FK15", "F15" },
    .{ "FK16", "F16" },
    .{ "FK17", "F17" },
    .{ "FK18", "F18" },
    .{ "FK19", "F19" },
    .{ "FK20", "F20" },
    .{ "FK21", "F21" },
    .{ "FK22", "F22" },
    .{ "FK23", "F23" },
    .{ "FK24", "F24" },
    .{ "I208", "PLAYCD" },
    .{ "I209", "PAUSECD" },
    .{ "I210", "PROG3" },
    .{ "I211", "PROG4" },
    .{ "I212", "ALL_APPLICATIONS" },
    .{ "I213", "DASHBOARD" },
    .{ "I214", "SUSPEND" },
    .{ "I215", "CLOSE" },
    .{ "I216", "PLAY" },
    .{ "I217", "FASTFORWARD" },
    .{ "I218", "BASSBOOST" },
    .{ "PRNT", "PRINT" },
    .{ "I220", "HP" },
    .{ "I221", "CAMERA" },
    .{ "I222", "SOUND" },
    .{ "I223", "QUESTION" },
    .{ "I224", "EMAIL" },
    .{ "I225", "CHAT" },
    .{ "I226", "SEARCH" },
    .{ "I227", "CONNECT" },
    .{ "I228", "FINANCE" },
    .{ "I229", "SPORT" },
    .{ "I230", "SHOP" },
    .{ "I231", "ALTERASE" },
    .{ "I232", "CANCEL" },
    .{ "I233", "BRIGHTNESSDOWN" },
    .{ "I234", "BRIGHTNESSUP" },
    .{ "I235", "MEDIA" },
    .{ "I236", "SWITCHVIDEOMODE" },
    .{ "I237", "KBDILLUMTOGGLE" },
    .{ "I238", "KBDILLUMDOWN" },
    .{ "I239", "KBDILLUMUP" },
    .{ "I240", "SEND" },
    .{ "I241", "REPLY" },
    .{ "I242", "FORWARDMAIL" },
    .{ "I243", "SAVE" },
    .{ "I244", "DOCUMENTS" },
    .{ "I245", "BATTERY" },
    .{ "I246", "BLUETOOTH" },
    .{ "I247", "WLAN" },
    .{ "I248", "UWB" },
    .{ "I249", "VIDEO_NEXT" },
    .{ "I250", "VIDEO_PREV" },
    .{ "I251", "BRIGHTNESS_CYCLE" },
    .{ "I252", "BRIGHTNESS_AUTO" },
    .{ "I253", "BRIGHTNESS_ZERO" },
    .{ "I254", "DISPLAY_OFF" },
    .{ "I255", "WWAN" },
    .{ "I256", "WIMAX" },
    .{ "I257", "RFKILL" },
    .{ "I258", "MICMUTE" },
});

pub const keycode_aliases = std.StaticStringMap([]const u8).initComptime(.{
    .{ "BACKSPACE", "BKSP" },

    .{ "MINUS", "-" },
    .{ "EQUAL", "=" },

    .{ "LEFTBRACE", "[" },
    .{ "RIGHTBRACE", "]" },

    .{ "SEMICOLON", ";" },
    .{ "APOSTROPHE", "'" },
    .{ "GRAVE", "`" },

    .{ "COMMA", "," },
    .{ "DOT", "." },
    .{ "SLASH", "/" },
    .{ "BACKSLASH", "\\" },

    .{ "LEFTSHIFT", "LSHIFT" },
    .{ "RIGHTSHIFT", "RSHIFT" },

    .{ "LEFTCTRL", "LCTRL" },
    .{ "RIGHTCTRL", "RCTRL" },

    .{ "LEFTALT", "LALT" },
    .{ "RIGHTALT", "RALT" },

    .{ "LEFTMETA", "LWIN" },
    .{ "RIGHTMETA", "RWIN" },

    .{ "CAPSLOCK", "CAPS" },
    .{ "102ND", "<" },

    .{ "PAGEUP", "PGUP" },
    .{ "PAGEDOWN", "PGDOWN" },

    .{ "INSERT", "INS" },
    .{ "DELETE", "DEL" },

    .{ "M1", "LMB" },
    .{ "M2", "RMB" },
    .{ "M3", "MMB" },
    .{ "M4", "MB4" },
    .{ "M5", "MB5" },
});

pub const untypeable_keycodes = std.StaticStringMap(void).initComptime(.{
    .{ "ESC", void },
    .{ "BACKSPACE", void },
    .{ "TAB", void },
    .{ "ENTER", void },
    .{ "LEFTCTRL", void },
    .{ "LEFTSHIFT", void },
    .{ "RIGHTSHIFT", void },
    .{ "LEFTALT", void },
    .{ "CAPSLOCK", void },
    .{ "NUMLOCK", void },
    .{ "SCROLLLOCK", void },
    .{ "RIGHTCTRL", void },
    .{ "KPENTER", void },
    .{ "HOME", void },
    .{ "UP", void },
    .{ "PAGEUP", void },
    .{ "LEFT", void },
    .{ "RIGHT", void },
    .{ "END", void },
    .{ "DOWN", void },
    .{ "PAGEDOWN", void },
    .{ "INSERT", void },
    .{ "DELETE", void },
    .{ "MACRO", void },
    .{ "MUTE", void },
    .{ "RIGHTCTRL", void },
    .{ "RIGHTALT", void },
    .{ "LEFTMETA", void },
    .{ "RIGHTMETA", void },

    .{ "F3", void },

    .{ "RO", void },
    .{ "KATAKANA", void },
    .{ "HIRAGANA", void },
    .{ "HENKAN", void },
    .{ "KATAKANAHIRAGANA", void },
    .{ "MUHENKAN", void },
    .{ "KPJPCOMMA", void },
    .{ "KPENTER", void },
    .{ "RIGHTCTRL", void },
    .{ "KPSLASH", void },
    .{ "SYSRQ", void },
    .{ "RIGHTALT", void },
    .{ "LINEFEED", void },
    .{ "HOME", void },
    .{ "UP", void },
    .{ "PAGEUP", void },
    .{ "LEFT", void },
    .{ "RIGHT", void },
    .{ "END", void },
    .{ "DOWN", void },
    .{ "PAGEDOWN", void },
    .{ "INSERT", void },
    .{ "DELETE", void },
    .{ "MACRO", void },
    .{ "MUTE", void },
    .{ "VOLUMEDOWN", void },
    .{ "VOLUMEUP", void },
    .{ "POWER", void },
    .{ "KPEQUAL", void },
    .{ "KPPLUSMINUS", void },
    .{ "PAUSE", void },
    .{ "SCALE", void },
    .{ "KPCOMMA", void },
    .{ "HANGEUL", void },
    .{ "HANGUEL", void },
    .{ "HANJA", void },
    .{ "YEN", void },
    .{ "LEFTMETA", void },
    .{ "RIGHTMETA", void },
    .{ "COMPOSE", void },
    .{ "STOP", void },
    .{ "AGAIN", void },
    .{ "PROPS", void },
    .{ "UNDO", void },
    .{ "FRONT", void },
    .{ "COPY", void },
    .{ "OPEN", void },
    .{ "PASTE", void },
    .{ "FIND", void },
    .{ "CUT", void },
    .{ "HELP", void },
    .{ "MENU", void },
    .{ "CALC", void },
    .{ "SETUP", void },
    .{ "SLEEP", void },
    .{ "WAKEUP", void },
    .{ "FILE", void },
    .{ "SENDFILE", void },
    .{ "DELETEFILE", void },
    .{ "XFER", void },
    .{ "PROG1", void },
    .{ "PROG2", void },
    .{ "WWW", void },
    .{ "MSDOS", void },
    .{ "COFFEE", void },
    .{ "SCREENLOCK", void },
    .{ "ROTATE_DISPLAY", void },
    .{ "DIRECTION", void },
    .{ "CYCLEWINDOWS", void },
    .{ "MAIL", void },
    .{ "BOOKMARKS", void },
    .{ "COMPUTER", void },
    .{ "BACK", void },
    .{ "FORWARD", void },
    .{ "CLOSECD", void },
    .{ "EJECTCD", void },
    .{ "EJECTCLOSECD", void },
    .{ "NEXTSONG", void },
    .{ "PLAYPAUSE", void },
    .{ "PREVIOUSSONG", void },
    .{ "STOPCD", void },
    .{ "RECORD", void },
    .{ "REWIND", void },
    .{ "PHONE", void },
    .{ "ISO", void },
    .{ "CONFIG", void },
    .{ "HOMEPAGE", void },
    .{ "REFRESH", void },
    .{ "EXIT", void },
    .{ "MOVE", void },
    .{ "EDIT", void },
    .{ "SCROLLUP", void },
    .{ "SCROLLDOWN", void },
    .{ "KPLEFTPAREN", void },
    .{ "KPRIGHTPAREN", void },
    .{ "NEW", void },
    .{ "REDO", void },
    .{ "PLAYCD", void },
    .{ "PAUSECD", void },
    .{ "PROG3", void },
    .{ "PROG4", void },
    .{ "ALL_APPLICATIONS", void },
    .{ "DASHBOARD", void },
    .{ "SUSPEND", void },
    .{ "CLOSE", void },
    .{ "PLAY", void },
    .{ "FASTFORWARD", void },
    .{ "BASSBOOST", void },
    .{ "PRINT", void },
    .{ "HP", void },
    .{ "CAMERA", void },
    .{ "SOUND", void },
    .{ "QUESTION", void },
    .{ "EMAIL", void },
    .{ "CHAT", void },
    .{ "SEARCH", void },
    .{ "CONNECT", void },
    .{ "FINANCE", void },
    .{ "SPORT", void },
    .{ "SHOP", void },
    .{ "ALTERASE", void },
    .{ "CANCEL", void },
    .{ "BRIGHTNESSDOWN", void },
    .{ "BRIGHTNESSUP", void },
    .{ "MEDIA", void },
    .{ "SWITCHVIDEOMODE", void },
    .{ "KBDILLUMTOGGLE", void },
    .{ "KBDILLUMDOWN", void },
    .{ "KBDILLUMUP", void },
    .{ "SEND", void },
    .{ "REPLY", void },
    .{ "FORWARDMAIL", void },
    .{ "SAVE", void },
    .{ "DOCUMENTS", void },
    .{ "BATTERY", void },
    .{ "BLUETOOTH", void },
    .{ "WLAN", void },
    .{ "UWB", void },
    .{ "VIDEO_NEXT", void },
    .{ "VIDEO_PREV", void },
    .{ "BRIGHTNESS_CYCLE", void },
    .{ "BRIGHTNESS_AUTO", void },
    .{ "BRIGHTNESS_ZERO", void },
    .{ "DISPLAY_OFF", void },
    .{ "WWAN", void },
    .{ "WIMAX", void },
    .{ "RFKILL", void },
    .{ "MICMUTE", void },

    .{ "M1", void },
    .{ "M2", void },
    .{ "M3", void },
    .{ "M4", void },
    .{ "M5", void },
});

pub const dvui_to_keycode: [std.meta.fields(dvui.enums.Key).len][]const u8 = .{
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",

    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",

    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "F13",
    "F14",
    "F15",
    "F16",
    "F17",
    "F18",
    "F19",
    "F20",
    "F21",
    "F22",
    "F23",
    "F24",
    "F25",

    "KPSLASH",
    "KPASTERISK",
    "KPMINUS",
    "KPPLUS",
    "KP0",
    "KP1",
    "KP2",
    "KP3",
    "KP4",
    "KP5",
    "KP6",
    "KP7",
    "KP8",
    "KP9",
    "KPDOT",
    "KPENTER",
    "KPENTER",

    "ENTER",
    "ESCAPE",
    "TAB",
    "LEFTSHIFT",
    "RIGHTSHIFT",
    "LEFTCTRL",
    "RIGHTCTRL",
    "LEFTALT",
    "RIGHTALT",
    "LEFTMETA",
    "RIGHTMETA",
    "MENU",
    "NUMLOCK",
    "CAPSLOCK",
    "PRINT",
    "SCROLLLOCK",
    "PAUSE",
    "DELETE",
    "HOME",
    "END",
    "PAGEUP",
    "PAGEDOWN",
    "INSERT",
    "LEFT",
    "RIGHT",
    "UP",
    "DOWN",
    "BACKSPACE",
    "SPACE",
    "MINUS",
    "EQUAL",
    "LEFTBRACE",
    "RIGHTBRACE",
    "BACKSLASH",
    "SEMICOLON",
    "APOSTROPHE",
    "COMMA",
    "PERIOD",
    "SLASH",
    "GRAVE",

    "UNKNOWN",
};
